### ISSUE TITLE
Set-Timezone not working

### ISSUE THREAD

**Issue by cwpfDUMMIES-7** [jaclu/ish-config#4]
I have installed ish-config, have executed Set Time Zone (US, Eastern), but alpine "date" utility puts out UTC.  I've done this several times.  
iSH is 1.3.3 (574)
Alpine is v3.18

**Comment by jaclu** [comment]
I did notice that the install procedure was missing the curl install step, so I added that.
I also updated set-timezone.sh to hopefully make it more stable.

I tried it on a fresh Alpine 3.18.5 miniroot filesystem selected US-Eastern. Once back at the prompt
date used the timezone EST

Let me know if it still doesnt work for you, and I will try to see if I can come up with something

**Comment by cwpfDUMMIES-7** [comment]
Thank You, 
I installed your latest code, set-Timezone to US/Eastern, 
and 
It's working now but it did require me to change one thing here: 
I'm booting to bash, my .bashrc file had this:
      export TZ=5
which made my local time correct in older versions of iSH + alpine.
I commented that line out, 
rebooted,
and "date" now returns my local time. 

cheers, 
cwpfDUMMIES-7

**Comment by jaclu** [comment]
set-timezone sets the system TZ, since on iSH you wouldnt normally have userts preferting different TZ. And by setting the system TZ, syslogs etc will use the intended TZ

If you really want to set a user specific TZ, you should instead do it as
export TZ=US/Eastern
